"""Scale test for fleet plan deconfliction (aerofleet/assurance/deconflict.py).

  python -m research.deconflict_scale            -> research/results/deconflict_scale.md

Synthetic but fixed workload, so every number is reproducible: six depots on a ring 3 km around Pune's
centre; each mission leaves a random depot for a random point 0.5-4 km away and returns; launch times
are uniform over a 10-minute window; three seeds per fleet size. Two cases:

  same height   every mission cruises at 60 m, horizontal-only rule (the CBF gate's rule): delays only
  layered       cruise heights drawn from 40/60/80/100 m, vertical separation allowed (20 m): height or delay

This measures the algorithm on plans. It says nothing about real flights, wind, or how well drones keep
to a schedule.
"""
from __future__ import annotations

import math
import random
import statistics
import time
from pathlib import Path

from aerofleet.assurance.deconflict import Mission, deconflict
from aerofleet.assurance.reconcile import Plan

CENTRE = (18.5204, 73.8567)
SIZES = (10, 25, 50, 100, 200, 300)
SEEDS = (20261008, 20261009, 20261010)
WINDOW_S, H_SEP = 600, 15.0
BANDS = (40.0, 60.0, 80.0, 100.0)


def _offset(lat, lon, bearing_deg, dist_m):
    b = math.radians(bearing_deg)
    return (lat + dist_m * math.cos(b) / 111_320.0, lon + dist_m * math.sin(b) / (111_320.0 * math.cos(math.radians(lat))))


DEPOTS = [_offset(*CENTRE, 60 * k, 3000) for k in range(6)]


def workload(n: int, seed: int, layered: bool):
    rng = random.Random(seed * 1000 + n)
    out = []
    for i in range(n):
        home = rng.choice(DEPOTS)
        dest = _offset(*home, rng.uniform(0, 360), rng.uniform(500, 4000))
        alt = rng.choice(BANDS) if layered else 60.0
        path = [(*home, 0.0), (*home, alt), (*dest, alt), (*home, alt), (*home, 0.0)]
        out.append(Mission(f"M{i:03d}", Plan(home, path, []), start_s=float(rng.randrange(0, WINDOW_S, 5))))
    return out


def run(n: int, layered: bool):
    rows = []
    for seed in SEEDS:
        ms = workload(n, seed, layered)
        t = time.perf_counter()
        r = deconflict(ms, h_sep_m=H_SEP, v_sep_m=20.0 if layered else None, altitude_bands_m=BANDS)
        secs = time.perf_counter() - t
        delays = [c["delay_s"] for c in r["changes"] if c["delay_s"]]
        involved = {x for c in r["before"] for x in (c["a"], c["b"])}
        rows.append({"before": len(r["before"]), "involved": len(involved), "after": len(r["after"]), "unresolved": len(r["unresolved"]),
                     "delayed": len(delays), "height": sum(1 for c in r["changes"] if c["new_altitude_m"] is not None),
                     "mean_delay": statistics.mean(delays) if delays else 0.0, "max_delay": max(delays, default=0.0), "secs": secs})
    m = lambda k: statistics.mean(x[k] for x in rows)  # noqa: E731
    return (f"| {n} | {m('before'):.1f} | {m('involved'):.1f} | {m('after'):.1f} | {m('unresolved'):.1f} | {m('delayed'):.1f} | "
            f"{m('height'):.1f} | {m('mean_delay'):.0f} | {max(x['max_delay'] for x in rows):.0f} | {m('secs'):.2f} |")


def main() -> None:
    head = ["| Missions | Conflicts before | Missions involved | Conflicts after | Unresolved | Delayed | Height changed | "
            "Mean delay (s) | Max delay (s) | Fix time (s) |", "|---|---|---|---|---|---|---|---|---|---|"]
    lines = ["# Fleet plan deconfliction — scale test", "",
             f"Generated by `python -m research.deconflict_scale`. Means over {len(SEEDS)} seeds; max delay is the largest over the seeds. "
             f"Launch window {WINDOW_S // 60} min, six depots 3 km from Pune's centre, legs 0.5-4 km, horizontal separation {H_SEP:.0f} m.", ""]
    for title, layered in (("Same height (60 m), horizontal-only rule — delays only", False),
                           ("Layered heights (40/60/80/100 m), vertical separation of 20 m allowed", True)):
        lines += [f"## {title}", ""] + head + [run(n, layered) for n in SIZES] + [""]
    lines += ["Synthetic plans only: no wind, straight legs, every drone assumed to launch on schedule and fly at 12 m/s."]
    out = Path("research/results/deconflict_scale.md")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
