"""Check the drift severity catalogue (aerofleet/assurance/drift.py) against the official parameter lists.

  python -m research.drift_catalogue_check --ardupilot apm.pdef.xml --px4 parameter_reference.md

Inputs (not committed; download them):
  ArduCopter  https://autotest.ardupilot.org/Parameters/ArduCopter/apm.pdef.xml
  PX4         https://raw.githubusercontent.com/PX4/PX4-Autopilot/main/docs/en/advanced_config/parameter_reference.md

Reports, per firmware: how many documented parameters fall in each severity; catalogue patterns that
match no documented parameter (a wrong or outdated name); and an independent cross-check — every
parameter whose own documentation mentions a failsafe or geofence but which the catalogue does not
rate CRITICAL. Writes research/results/drift_catalogue_check.md.
"""
from __future__ import annotations

import argparse
import re
import xml.etree.ElementTree as ET
from collections import Counter
from fnmatch import fnmatchcase
from pathlib import Path
from typing import Dict, List

from aerofleet.assurance.drift import CATALOGUE, CRITICAL, IGNORED_PATTERNS, LEGACY_PATTERNS, severity_of

KEYWORDS = re.compile(r"fail-?safe|geo-?fence|\bfence\b", re.I)


def ardupilot_params(path: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for p in ET.parse(path).getroot().iter("param"):
        name = p.get("name", "").split(":")[-1]
        if name:
            out[name] = f"{p.get('humanName', '')}. {p.get('documentation', '')}"
    return out


def px4_params(path: str) -> Dict[str, str]:
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    parts = re.split(r"^### ([A-Z0-9_]+) \(`[A-Z0-9]+`\).*$", text, flags=re.M)
    return {parts[i]: parts[i + 1][:600] for i in range(1, len(parts) - 1, 2)}


def analyse(label: str, params: Dict[str, str], lines: List[str]) -> None:
    sev = Counter(severity_of(n) or "IGNORED" for n in params)
    lines += [f"## {label}", "", f"Documented parameters: **{len(params)}**", "",
              "| Severity | Parameters | Share |", "|---|---|---|"]
    for s in ("CRITICAL", "HIGH", "TUNING", "INFO", "IGNORED"):
        lines.append(f"| {s} | {sev[s]} | {100 * sev[s] / len(params):.1f}% |")
    flagged = sorted(n for n, doc in params.items() if KEYWORDS.search(doc))
    missed = [n for n in flagged if severity_of(n) != CRITICAL]
    lines += ["", f"Cross-check: **{len(flagged)}** parameters mention a failsafe or geofence in their own documentation; "
              f"the catalogue rates **{len(flagged) - len(missed)}** of them CRITICAL and **{len(missed)}** lower.", ""]
    if missed:
        lines += ["Rated lower than CRITICAL (review each — some only mention a failsafe in passing):", ""]
        lines += [f"- `{n}` ({severity_of(n) or 'IGNORED'}): {params[n][:110].strip()}" for n in missed] + [""]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ardupilot", required=True)
    ap.add_argument("--px4", required=True)
    ap.add_argument("--out", default="research/results/drift_catalogue_check.md")
    a = ap.parse_args()
    fw = {"ArduPilot Copter": ardupilot_params(a.ardupilot), "PX4": px4_params(a.px4)}
    lines = ["# Drift severity catalogue checked against the official parameter lists", "",
             "Generated by `python -m research.drift_catalogue_check`. Catalogue: `aerofleet/assurance/drift.py`.", ""]
    for label, params in fw.items():
        analyse(label, params, lines)
    every = set().union(*fw.values())
    patterns = [(sev, p) for sev, pats in CATALOGUE for p in pats] + [("IGNORED", p) for p in IGNORED_PATTERNS]
    dead = [(sev, p) for sev, p in patterns if not any(fnmatchcase(n, p) for n in every)]
    legacy = [(sev, p) for sev, p in dead if p in LEGACY_PATTERNS]
    wrong = [(sev, p) for sev, p in dead if p not in LEGACY_PATTERNS]
    lines += ["## Catalogue patterns that match no documented parameter", "",
              f"{len(dead)} of {len(patterns)} patterns match nothing in either current list: {len(legacy)} are older-firmware "
              f"spellings kept on purpose, {len(wrong)} are unexplained (wrong or removed names).", "",
              "Kept for older firmware: " + (", ".join(f"`{p}`" for _, p in legacy) or "none"), "",
              "Unexplained: " + (", ".join(f"`{p}` ({sev})" for sev, p in wrong) or "none"), ""]
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
