"""Redis pub/sub bridge for AsyncEventBus (Phase AH).

The problem this solves: aerofleet/api/routes/hardware.py's WebSocket
telemetry stream only fans out events published on THIS process's own
in-memory AsyncEventBus. In a multi-worker deployment (`--workers N`), a
WebSocket client connected to worker B never sees telemetry generated by
worker A's DroneLinkRegistry, because nothing bridges the two processes'
event buses. This module is that bridge — additive and env-gated
(AEROFLEET_REDIS_URL): unset, get_redis_client() returns None and
RedisEventBridge behaves as a pure pass-through to the local bus, so
existing single-process behavior is unchanged.

What this does NOT solve (see docs/MULTI_WORKER_ARCHITECTURE.md for the
full design and why): it does not give every worker a synchronized,
read-consistent copy of FleetState, and it does not make dispatch/hardware
*mutations* safe to accept on more than one worker. A MAVLink link is a
single-owner resource regardless of what's in Redis — see
AEROFLEET_HARDWARE_OWNER in aerofleet/api/routes/hardware.py.
"""
from __future__ import annotations

import asyncio
import json
import os
import uuid
from dataclasses import asdict
from typing import Callable, Optional

from aerofleet.event_bus.async_bus import Event
from aerofleet.utils.logging import get_logger

logger = get_logger(__name__)

REDIS_CHANNEL = "aerofleet:events"

# One random id per process — tags every event this process relays to
# Redis, so this same process's own Redis subscription can skip it on the
# way back in instead of double-dispatching it to its local WS clients.
_PROCESS_ID = uuid.uuid4().hex


def get_redis_url() -> Optional[str]:
    return os.environ.get("AEROFLEET_REDIS_URL") or None


def get_redis_client():
    """Returns an async redis client, or None if AEROFLEET_REDIS_URL isn't
    set. Never raises on a missing/unreachable Redis — callers treat None
    (or a later connection failure) as "run in single-process mode"."""
    url = get_redis_url()
    if not url:
        return None
    import redis.asyncio as redis

    return redis.Redis.from_url(url, decode_responses=True)


class RedisEventBridge:
    """relay_to_redis() is called from an existing local event-bus
    subscriber (the event has already been dispatched locally by the
    normal AsyncEventBus.publish() path — this only sends a copy to every
    OTHER worker process via Redis pub/sub). listen_forever() is the
    receiving half — runs as a background task, invoking on_relayed_event
    for each event that arrived from another process.

    Deliberately does NOT re-publish received events back onto a local
    AsyncEventBus's normal subscriber list: that subscriber list already
    includes the very handler that calls relay_to_redis(), so doing so
    would re-relay a received event straight back out to Redis — an
    unbounded ping-pong loop across every worker. on_relayed_event should
    go straight to whatever the local effect is (e.g. broadcasting to this
    process's own WebSocket clients), bypassing relay entirely."""

    def __init__(self, on_relayed_event: Callable[[Event], None]):
        self._on_relayed_event = on_relayed_event
        self._redis = get_redis_client()
        self._pubsub = None
        self._running = False

    @property
    def redis_enabled(self) -> bool:
        return self._redis is not None

    async def relay_to_redis(self, event: Event) -> None:
        if self._redis is None:
            return
        try:
            payload = json.dumps({"origin": _PROCESS_ID, "event": asdict(event)})
            await self._redis.publish(REDIS_CHANNEL, payload)
        except Exception as exc:
            # A relay failure must never take down the local telemetry
            # path — this worker's own clients already got the event via
            # the normal local dispatch that triggered this call; they
            # just won't see other workers' events until Redis recovers.
            logger.error(f"Redis event relay failed (continuing local-only): {exc}")

    async def listen_forever(self) -> None:
        if self._redis is None:
            logger.info("AEROFLEET_REDIS_URL not set — RedisEventBridge running local-only")
            return
        self._running = True
        try:
            self._pubsub = self._redis.pubsub()
            await self._pubsub.subscribe(REDIS_CHANNEL)
            logger.info(f"RedisEventBridge subscribed to '{REDIS_CHANNEL}'")
            while self._running:
                message = await self._pubsub.get_message(ignore_subscribe_messages=True, timeout=1.0)
                if message is None:
                    continue
                await self._handle_message(message)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.error(f"RedisEventBridge listener stopped unexpectedly: {exc}")
        finally:
            if self._pubsub is not None:
                await self._pubsub.close()

    async def _handle_message(self, message) -> None:
        try:
            envelope = json.loads(message["data"])
        except (TypeError, ValueError, KeyError):
            return
        if envelope.get("origin") == _PROCESS_ID:
            return  # our own relayed event, already dispatched locally
        event_dict = envelope.get("event", {})
        try:
            event = Event(**event_dict)
        except TypeError:
            logger.warning(f"RedisEventBridge received malformed event envelope: {envelope}")
            return
        self._on_relayed_event(event)

    def stop(self) -> None:
        self._running = False
