from fpdf import FPDF
import os
from datetime import datetime
import re

class MissionReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Mission Definition Review (MDR)', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 5, f'Generated by SMA-X Architect | {datetime.now().strftime("%Y-%m-%d")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        # Footer with Page Number
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        # Section Header with Background Color
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(230, 240, 255) # Light Blue
        self.cell(0, 8, f'{label}', 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        # Body Text
        self.set_font('Arial', '', 11)
        clean_text = self.sanitize(str(text))
        self.multi_cell(0, 6, clean_text)
        self.ln()

    def add_metric(self, label, value):
        # Key-Value Pair Row
        self.set_font('Arial', 'B', 11)
        self.cell(60, 6, f"{label}:", 0, 0)
        self.set_font('Arial', '', 11)
        clean_val = self.sanitize(str(value))
        self.cell(0, 6, clean_val, 0, 1)

    def sanitize(self, text):
        """
        Removes Emojis and non-Latin-1 characters to prevent FPDF crash.
        """
        if not isinstance(text, str): return str(text)
        # Encode to latin-1 (ignoring errors drops emojis), then decode back
        return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf(sim, mrd_text, transcript=None, filename="Mission_Report.pdf"):
    """
    Generates a PDF report. 
    Args:
        sim: The MissionSimulation object containing specs.
        mrd_text: The summarized mission brief.
        transcript: (Optional) List of dicts from the Council Debate.
    """
    pdf = MissionReport()
    pdf.add_page()
    
    # 1. EXECUTIVE SUMMARY
    pdf.chapter_title("1. Mission Executive Summary")
    # Using dictionary access for fields that don't have direct properties in MissionCore
    pdf.add_metric("Mission Name", sim.specs.overview.get('name', 'Unknown'))
    pdf.add_metric("Mission Type", sim.specs.overview.get('type', 'Unknown'))
    pdf.add_metric("Target Destination", sim.specs.orbit['target'].get('type', 'Unknown'))
    pdf.add_metric("Primary Propulsion", sim.specs.configuration['propulsion'].get('type', 'Unknown'))
    pdf.add_metric("Power Architecture", sim.specs.configuration['power'].get('type', 'Unknown'))
    pdf.ln(5)
    
    # 2. SPACECRAFT CONFIGURATION
    pdf.chapter_title("2. Hardware Specifications")
    
    # Access nested configuration data safely
    phys = sim.specs.configuration.get('physical', {})
    prop = sim.specs.configuration.get('propulsion', {})
    
    pdf.add_metric("Payload Mass", f"{phys.get('payload_mass', 0)} kg")
    pdf.add_metric("Dry Mass (Est)", f"{phys.get('mass_dry', 0)} kg")
    pdf.add_metric("Wet Mass (Total)", f"{phys.get('mass_wet', 0)} kg")
    pdf.add_metric("Propellant Mass", f"{prop.get('propellant_mass', 0)} kg")
    
    # Financials
    pdf.add_metric("Budget Cap", f"${sim.specs.financials.get('budget_cap_m', 0)} M")
    pdf.add_metric("Est. Cost", f"${sim.specs.financials.get('cost_estimate_m', 0)} M")
    pdf.ln(5)
    
    # 3. TRAJECTORY & OPS
    pdf.chapter_title("3. Flight Dynamics Profile")
    if sim.mission_plan:
        launch_d = sim.mission_plan.get('launch_date', 'TBD')
        if isinstance(launch_d, datetime): launch_d = launch_d.strftime("%Y-%m-%d")
        
        pdf.add_metric("Launch Date", launch_d)
        pdf.add_metric("Required Delta-V", f"{sim.mission_plan.get('estimated_delta_v_km_s', 0):.2f} km/s")
    else:
        pdf.chapter_body("Trajectory calculation has not been finalized yet.")
    pdf.ln(5)
    
    # 4. COUNCIL DEBATE TRANSCRIPT (If Available)
    if transcript:
        pdf.chapter_title("4. Council of Experts - Debate Transcript")
        for entry in transcript:
            role = entry.get('role', 'Unknown').upper()
            if role == "SYSTEM": continue # Skip system logs
            
            name = entry.get('name', role)
            text = entry.get('text', '')
            verdict = entry.get('verdict', '')
            
            # Format: [VERDICT] Role (Name): Text
            header = f"[{verdict}] {name}" if verdict else f"{name}"
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(0, 6, pdf.sanitize(header), 0, 1)
            
            pdf.set_font('Arial', '', 10)
            pdf.multi_cell(0, 5, pdf.sanitize(text))
            pdf.ln(2)
        pdf.ln(5)

    # 5. SYSTEM REQUIREMENTS (AI GENERATED)
    pdf.chapter_title("5. Detailed Mission Requirements (MRD)")
    # Clean up markdown formatting for PDF
    clean_text = mrd_text.replace('**', '').replace('##', '')
    pdf.chapter_body(clean_text)
    
    # Output
    try:
        pdf.output(filename)
        return filename
    except Exception as e:
        print(f"PDF Gen Error: {e}")
        return "Error_Generating_PDF.pdf"